### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by dishcandanty** [DreaminginCodeZH/deadbeef-gnome-mmkeys#10]
Dunno if this would be helpful for other people. But after these steps, I was able to successfully use this plugin! 

```
sudo apt-get install libglib2.0-dev # 
sudo add-apt-repository ppa:starws-box/deadbeef-player
sudo apt-get update
sudo apt-get install -y deadbeef-plugins-dev
make install
sudo make install
```

Make sure you don't have ubuntu's default deadbeef installed (or you will have two copies installed).

Don't think there are any specific action items, just wanting to be helpful on the steps I needed, so going to be closing.

**Comment by almartinch** [comment]
had to figure it out by myself for around and hour lol, thanks

if by any chance somebody wants to grab this extension again and is just looking for your gnome+deadbeef multimedia keys to work on Ubuntu 20+ (yes, not develop for), just do:
- add ppa:/alex-p/deadbeef
- install deadbeef deadbeef-mpris2-plugin
- grab the binary for this awesome plugin from here: https://deadbeef.sourceforge.io/plugins.html (look for `GNOME multimedia keys support`)
