### ISSUE TITLE
ddb_gnome_mmkeys.c:44:31: fatal error: deadbeef/deadbeef.h: No such file or directory

### ISSUE THREAD

**Issue by amartin1911** [DreaminginCodeZH/deadbeef-gnome-mmkeys#5]
After cloning an entering the directory, 'make' gives this fatal error:
ddb_gnome_mmkeys.c:44:31: fatal error: deadbeef/deadbeef.h: No such file or directory

The full output is:
~/git/deadbeef-gnome-mmkeys$ make
gcc -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fPIC -shared -o ddb_gnome_mmkeys.so ddb_gnome_mmkeys.c -lgio-2.0 -lgobject-2.0 -lglib-2.0
ddb_gnome_mmkeys.c:44:31: fatal error: deadbeef/deadbeef.h: No such file or directory
compilation terminated.
Makefile:14: recipe for target 'ddb_gnome_mmkeys.so' failed
make: *** [ddb_gnome_mmkeys.so] Error 1

I'm using Ubuntu 16.04 LTS with Gnome 3

**Comment by DreaminginCodeZH** [comment]
Did you have `deadbeaf` installed? On Arch Linux I have `/usr/include/deadbeef/deadbeef.h` once I installed it.

Or perhaps something like `deadbeaf-dev` for Ubuntu?

**Comment by amartin1911** [comment]
Yes, I've installed it through this PPA:
http://ppa.launchpad.net/starws-box/deadbeef-player/ubuntu

My current deadbeef version is 0.7.2-1~xenial~ppa1

Checking the installed files on Synaptic gives me this long list where the file "deadbeef.h" is not present:

/.
/usr
/usr/bin
/usr/bin/deadbeef
/usr/lib
/usr/lib/deadbeef
/usr/lib/deadbeef/aac.so
/usr/lib/deadbeef/adplug.so
/usr/lib/deadbeef/alac.so
/usr/lib/deadbeef/alsa.so
/usr/lib/deadbeef/artwork.so
/usr/lib/deadbeef/cdda.so
/usr/lib/deadbeef/converter.so
/usr/lib/deadbeef/converter_gtk2.so
/usr/lib/deadbeef/converter_gtk3.so
/usr/lib/deadbeef/convpresets
/usr/lib/deadbeef/convpresets/AAC_(Nero_FAAC).txt
/usr/lib/deadbeef/convpresets/ALAC.txt
/usr/lib/deadbeef/convpresets/FLAC_(compression_level_5).txt
/usr/lib/deadbeef/convpresets/MP3_CBR_320_Kbps_(Lame).txt
/usr/lib/deadbeef/convpresets/MP3_VBR_192Kbps_(Lame).txt
/usr/lib/deadbeef/convpresets/MS_RIFF_WAV.txt
/usr/lib/deadbeef/convpresets/MusePack.txt
/usr/lib/deadbeef/convpresets/Ogg_FLAC.txt
/usr/lib/deadbeef/convpresets/Ogg_Vorbis_(-q_5).txt
/usr/lib/deadbeef/convpresets/Opus.txt
/usr/lib/deadbeef/convpresets/TTA.txt
/usr/lib/deadbeef/convpresets/WavPack.txt
/usr/lib/deadbeef/data68
/usr/lib/deadbeef/data68/Replay
/usr/lib/deadbeef/data68/Replay/aenigmatica.bin
/usr/lib/deadbeef/data68/Replay/alteredbeast.bin
/usr/lib/deadbeef/data68/Replay/armalyte.bin
/usr/lib/deadbeef/data68/Replay/asidifier.bin
/usr/lib/deadbeef/data68/Replay/azidifier.bin
/usr/lib/deadbeef/data68/Replay/bendaglish.deli.bin
/usr/lib/deadbeef/data68/Replay/big.bin
/usr/lib/deadbeef/data68/Replay/blipblop.bin
/usr/lib/deadbeef/data68/Replay/blipp079.bin
/usr/lib/deadbeef/data68/Replay/bs22.bin
/usr/lib/deadbeef/data68/Replay/cabal.bin
/usr/lib/deadbeef/data68/Replay/chipmon2.bin
/usr/lib/deadbeef/data68/Replay/cosotfmx.bin
/usr/lib/deadbeef/data68/Replay/crapman1.bin
/usr/lib/deadbeef/data68/Replay/crapman2.bin
/usr/lib/deadbeef/data68/Replay/deltamusic1.bin
/usr/lib/deadbeef/data68/Replay/deltamusic2.bin
/usr/lib/deadbeef/data68/Replay/digitfmx.bin
/usr/lib/deadbeef/data68/Replay/dmu.bin
/usr/lib/deadbeef/data68/Replay/dwaga.bin
/usr/lib/deadbeef/data68/Replay/dyter07.bin
/usr/lib/deadbeef/data68/Replay/elf.bin
/usr/lib/deadbeef/data68/Replay/fc13_14.bin
/usr/lib/deadbeef/data68/Replay/fireice.bin
/usr/lib/deadbeef/data68/Replay/fred.bin
/usr/lib/deadbeef/data68/Replay/gemx.bin
/usr/lib/deadbeef/data68/Replay/harlequin.bin
/usr/lib/deadbeef/data68/Replay/hippel-coso_note.deli.bin
/usr/lib/deadbeef/data68/Replay/hpn-jam.bin
/usr/lib/deadbeef/data68/Replay/huelsbeck.bin
/usr/lib/deadbeef/data68/Replay/huntforredoct.bin
/usr/lib/deadbeef/data68/Replay/ivanhoe.bin
/usr/lib/deadbeef/data68/Replay/jamcracker10.bin
/usr/lib/deadbeef/data68/Replay/jamcrackerpro.bin
/usr/lib/deadbeef/data68/Replay/lastninja3.bin
/usr/lib/deadbeef/data68/Replay/lastninjaiii.bin
/usr/lib/deadbeef/data68/Replay/lcd.bin
/usr/lib/deadbeef/data68/Replay/lx_mmme.bin
/usr/lib/deadbeef/data68/Replay/mcoder.bin
/usr/lib/deadbeef/data68/Replay/megatizer.bin
/usr/lib/deadbeef/data68/Replay/metrocross.bin
/usr/lib/deadbeef/data68/Replay/midi.bin
/usr/lib/deadbeef/data68/Replay/mmme.bin
/usr/lib/deadbeef/data68/Replay/mmmesid.bin
/usr/lib/deadbeef/data68/Replay/mon.bin
/usr/lib/deadbeef/data68/Replay/mon_old.deli.bin
/usr/lib/deadbeef/data68/Replay/musmon1.bin
/usr/lib/deadbeef/data68/Replay/musmon2.bin
/usr/lib/deadbeef/data68/Replay/ninjaremix.bin
/usr/lib/deadbeef/data68/Replay/ninjatfmx.bin
/usr/lib/deadbeef/data68/Replay/nobuddiesland.bin
/usr/lib/deadbeef/data68/Replay/none.bin
/usr/lib/deadbeef/data68/Replay/note.bin
/usr/lib/deadbeef/data68/Replay/note2.bin
/usr/lib/deadbeef/data68/Replay/page.bin
/usr/lib/deadbeef/data68/Replay/protracker.bin
/usr/lib/deadbeef/data68/Replay/psg1.bin
/usr/lib/deadbeef/data68/Replay/psgtrackerv2.bin
/usr/lib/deadbeef/data68/Replay/puma.bin
/usr/lib/deadbeef/data68/Replay/puma2.bin
/usr/lib/deadbeef/data68/Replay/quartet.bin
/usr/lib/deadbeef/data68/Replay/quartet_mindbomb.bin
/usr/lib/deadbeef/data68/Replay/realms.bin
/usr/lib/deadbeef/data68/Replay/robhubbard.deli.bin
/usr/lib/deadbeef/data68/Replay/rollingronny.bin
/usr/lib/deadbeef/data68/Replay/shadowdancer.bin
/usr/lib/deadbeef/data68/Replay/sidmon1.bin
/usr/lib/deadbeef/data68/Replay/sidmon2.bin
/usr/lib/deadbeef/data68/Replay/sidsound.bin
/usr/lib/deadbeef/data68/Replay/sndh_ice.bin
/usr/lib/deadbeef/data68/Replay/soundfx.bin
/usr/lib/deadbeef/data68/Replay/spacecrusade.bin
/usr/lib/deadbeef/data68/Replay/spacegun.bin
/usr/lib/deadbeef/data68/Replay/ssd1.bin
/usr/lib/deadbeef/data68/Replay/stos.bin
/usr/lib/deadbeef/data68/Replay/synthiv.bin
/usr/lib/deadbeef/data68/Replay/tao_digi.bin
/usr/lib/deadbeef/data68/Replay/tao_hubbard.bin
/usr/lib/deadbeef/data68/Replay/tao_ms211.bin
/usr/lib/deadbeef/data68/Replay/tao_ms25.bin
/usr/lib/deadbeef/data68/Replay/tao_ms27.bin
/usr/lib/deadbeef/data68/Replay/tao_tsd.bin
/usr/lib/deadbeef/data68/Replay/tcbtracker.bin
/usr/lib/deadbeef/data68/Replay/test.bin
/usr/lib/deadbeef/data68/Replay/tfmx.bin
/usr/lib/deadbeef/data68/Replay/tfmx_aga.bin
/usr/lib/deadbeef/data68/Replay/tfmx_old.bin
/usr/lib/deadbeef/data68/Replay/tfmx_st.bin
/usr/lib/deadbeef/data68/Replay/timerc.bin
/usr/lib/deadbeef/data68/Replay/toki.bin
/usr/lib/deadbeef/data68/Replay/tsd1.bin
/usr/lib/deadbeef/data68/Replay/utopia.bin
/usr/lib/deadbeef/data68/Replay/vikingchild.bin
/usr/lib/deadbeef/data68/Replay/xbiossound.bin
/usr/lib/deadbeef/data68/Replay/zonewarrior.bin
/usr/lib/deadbeef/dca.so
/usr/lib/deadbeef/ddb_ao.so
/usr/lib/deadbeef/ddb_dumb.so
/usr/lib/deadbeef/ddb_gui_GTK2.so
/usr/lib/deadbeef/ddb_gui_GTK3.so
/usr/lib/deadbeef/ddb_mono2stereo.so
/usr/lib/deadbeef/ddb_shn.so
/usr/lib/deadbeef/dsp_libsrc.so
/usr/lib/deadbeef/ffap.so
/usr/lib/deadbeef/ffmpeg.so
/usr/lib/deadbeef/flac.so
/usr/lib/deadbeef/gme.so
/usr/lib/deadbeef/hotkeys.so
/usr/lib/deadbeef/in_sc68.so
/usr/lib/deadbeef/lastfm.so
/usr/lib/deadbeef/m3u.so
/usr/lib/deadbeef/mms.so
/usr/lib/deadbeef/mp3.so
/usr/lib/deadbeef/musepack.so
/usr/lib/deadbeef/notify.so
/usr/lib/deadbeef/nullout.so
/usr/lib/deadbeef/oss.so
/usr/lib/deadbeef/pltbrowser_gtk2.so
/usr/lib/deadbeef/pltbrowser_gtk3.so
/usr/lib/deadbeef/pulse.so
/usr/lib/deadbeef/shellexec.so
/usr/lib/deadbeef/shellexecui_gtk2.so
/usr/lib/deadbeef/shellexecui_gtk3.so
/usr/lib/deadbeef/sid.so
/usr/lib/deadbeef/sndfile.so
/usr/lib/deadbeef/supereq.so
/usr/lib/deadbeef/tta.so
/usr/lib/deadbeef/vfs_curl.so
/usr/lib/deadbeef/vfs_zip.so
/usr/lib/deadbeef/vorbis.so
/usr/lib/deadbeef/vtx.so
/usr/lib/deadbeef/wavpack.so
/usr/lib/deadbeef/wildmidi.so
/usr/lib/deadbeef/wma.so
/usr/share
/usr/share/applications
/usr/share/applications/deadbeef.desktop
/usr/share/deadbeef
/usr/share/deadbeef/pixmaps
/usr/share/deadbeef/pixmaps/buffering_16.png
/usr/share/deadbeef/pixmaps/noartwork.png
/usr/share/deadbeef/pixmaps/pause_16.png
/usr/share/deadbeef/pixmaps/play_16.png
/usr/share/doc
/usr/share/doc/deadbeef
/usr/share/doc/deadbeef/COPYING.GPLv2
/usr/share/doc/deadbeef/COPYING.LGPLv2.1
/usr/share/doc/deadbeef/ChangeLog
/usr/share/doc/deadbeef/about.txt
/usr/share/doc/deadbeef/changelog.Debian.gz
/usr/share/doc/deadbeef/copyright
/usr/share/doc/deadbeef/help.pt_BR.txt
/usr/share/doc/deadbeef/help.ru.txt
/usr/share/doc/deadbeef/help.txt
/usr/share/doc/deadbeef/translators.txt
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/128x128
/usr/share/icons/hicolor/128x128/apps
/usr/share/icons/hicolor/128x128/apps/deadbeef.png
/usr/share/icons/hicolor/16x16
/usr/share/icons/hicolor/16x16/apps
/usr/share/icons/hicolor/16x16/apps/deadbeef.png
/usr/share/icons/hicolor/192x192
/usr/share/icons/hicolor/192x192/apps
/usr/share/icons/hicolor/192x192/apps/deadbeef.png
/usr/share/icons/hicolor/22x22
/usr/share/icons/hicolor/22x22/apps
/usr/share/icons/hicolor/22x22/apps/deadbeef.png
/usr/share/icons/hicolor/24x24
/usr/share/icons/hicolor/24x24/apps
/usr/share/icons/hicolor/24x24/apps/deadbeef.png
/usr/share/icons/hicolor/256x256
/usr/share/icons/hicolor/256x256/apps
/usr/share/icons/hicolor/256x256/apps/deadbeef.png
/usr/share/icons/hicolor/32x32
/usr/share/icons/hicolor/32x32/apps
/usr/share/icons/hicolor/32x32/apps/deadbeef.png
/usr/share/icons/hicolor/36x36
/usr/share/icons/hicolor/36x36/apps
/usr/share/icons/hicolor/36x36/apps/deadbeef.png
/usr/share/icons/hicolor/48x48
/usr/share/icons/hicolor/48x48/apps
/usr/share/icons/hicolor/48x48/apps/deadbeef.png
/usr/share/icons/hicolor/64x64
/usr/share/icons/hicolor/64x64/apps
/usr/share/icons/hicolor/64x64/apps/deadbeef.png
/usr/share/icons/hicolor/72x72
/usr/share/icons/hicolor/72x72/apps
/usr/share/icons/hicolor/72x72/apps/deadbeef.png
/usr/share/icons/hicolor/96x96
/usr/share/icons/hicolor/96x96/apps
/usr/share/icons/hicolor/96x96/apps/deadbeef.png
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/deadbeef.svg
/usr/share/locale
/usr/share/locale/be
/usr/share/locale/be/LC_MESSAGES
/usr/share/locale/be/LC_MESSAGES/deadbeef.mo
/usr/share/locale/bg
/usr/share/locale/bg/LC_MESSAGES
/usr/share/locale/bg/LC_MESSAGES/deadbeef.mo
/usr/share/locale/bn
/usr/share/locale/bn/LC_MESSAGES
/usr/share/locale/bn/LC_MESSAGES/deadbeef.mo
/usr/share/locale/ca
/usr/share/locale/ca/LC_MESSAGES
/usr/share/locale/ca/LC_MESSAGES/deadbeef.mo
/usr/share/locale/cs
/usr/share/locale/cs/LC_MESSAGES
/usr/share/locale/cs/LC_MESSAGES/deadbeef.mo
/usr/share/locale/da
/usr/share/locale/da/LC_MESSAGES
/usr/share/locale/da/LC_MESSAGES/deadbeef.mo
/usr/share/locale/de
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/deadbeef.mo
/usr/share/locale/el
/usr/share/locale/el/LC_MESSAGES
/usr/share/locale/el/LC_MESSAGES/deadbeef.mo
/usr/share/locale/en_GB
/usr/share/locale/en_GB/LC_MESSAGES
/usr/share/locale/en_GB/LC_MESSAGES/deadbeef.mo
/usr/share/locale/es
/usr/share/locale/es/LC_MESSAGES
/usr/share/locale/es/LC_MESSAGES/deadbeef.mo
/usr/share/locale/et
/usr/share/locale/et/LC_MESSAGES
/usr/share/locale/et/LC_MESSAGES/deadbeef.mo
/usr/share/locale/eu
/usr/share/locale/eu/LC_MESSAGES
/usr/share/locale/eu/LC_MESSAGES/deadbeef.mo
/usr/share/locale/fa
/usr/share/locale/fa/LC_MESSAGES
/usr/share/locale/fa/LC_MESSAGES/deadbeef.mo
/usr/share/locale/fi
/usr/share/locale/fi/LC_MESSAGES
/usr/share/locale/fi/LC_MESSAGES/deadbeef.mo
/usr/share/locale/fr
/usr/share/locale/fr/LC_MESSAGES
/usr/share/locale/fr/LC_MESSAGES/deadbeef.mo
/usr/share/locale/gl
/usr/share/locale/gl/LC_MESSAGES
/usr/share/locale/gl/LC_MESSAGES/deadbeef.mo
/usr/share/locale/he
/usr/share/locale/he/LC_MESSAGES
/usr/share/locale/he/LC_MESSAGES/deadbeef.mo
/usr/share/locale/hr
/usr/share/locale/hr/LC_MESSAGES
/usr/share/locale/hr/LC_MESSAGES/deadbeef.mo
/usr/share/locale/hu
/usr/share/locale/hu/LC_MESSAGES
/usr/share/locale/hu/LC_MESSAGES/deadbeef.mo
/usr/share/locale/id
/usr/share/locale/id/LC_MESSAGES
/usr/share/locale/id/LC_MESSAGES/deadbeef.mo
/usr/share/locale/it
/usr/share/locale/it/LC_MESSAGES
/usr/share/locale/it/LC_MESSAGES/deadbeef.mo
/usr/share/locale/ja
/usr/share/locale/ja/LC_MESSAGES
/usr/share/locale/ja/LC_MESSAGES/deadbeef.mo
/usr/share/locale/kk
/usr/share/locale/kk/LC_MESSAGES
/usr/share/locale/kk/LC_MESSAGES/deadbeef.mo
/usr/share/locale/km
/usr/share/locale/km/LC_MESSAGES
/usr/share/locale/km/LC_MESSAGES/deadbeef.mo
/usr/share/locale/lg
/usr/share/locale/lg/LC_MESSAGES
/usr/share/locale/lg/LC_MESSAGES/deadbeef.mo
/usr/share/locale/lt
/usr/share/locale/lt/LC_MESSAGES
/usr/share/locale/lt/LC_MESSAGES/deadbeef.mo
/usr/share/locale/lv
/usr/share/locale/lv/LC_MESSAGES
/usr/share/locale/lv/LC_MESSAGES/deadbeef.mo
/usr/share/locale/nl
/usr/share/locale/nl/LC_MESSAGES
/usr/share/locale/nl/LC_MESSAGES/deadbeef.mo
/usr/share/locale/pl
/usr/share/locale/pl/LC_MESSAGES
/usr/share/locale/pl/LC_MESSAGES/deadbeef.mo
/usr/share/locale/pt
/usr/share/locale/pt/LC_MESSAGES
/usr/share/locale/pt/LC_MESSAGES/deadbeef.mo
/usr/share/locale/pt_BR
/usr/share/locale/pt_BR/LC_MESSAGES
/usr/share/locale/pt_BR/LC_MESSAGES/deadbeef.mo
/usr/share/locale/ro
/usr/share/locale/ro/LC_MESSAGES
/usr/share/locale/ro/LC_MESSAGES/deadbeef.mo
/usr/share/locale/ru
/usr/share/locale/ru/LC_MESSAGES
/usr/share/locale/ru/LC_MESSAGES/deadbeef.mo
/usr/share/locale/si_LK
/usr/share/locale/si_LK/LC_MESSAGES
/usr/share/locale/si_LK/LC_MESSAGES/deadbeef.mo
/usr/share/locale/sk
/usr/share/locale/sk/LC_MESSAGES
/usr/share/locale/sk/LC_MESSAGES/deadbeef.mo
/usr/share/locale/sl
/usr/share/locale/sl/LC_MESSAGES
/usr/share/locale/sl/LC_MESSAGES/deadbeef.mo
/usr/share/locale/sr
/usr/share/locale/sr/LC_MESSAGES
/usr/share/locale/sr/LC_MESSAGES/deadbeef.mo
/usr/share/locale/sr@latin
/usr/share/locale/sr@latin/LC_MESSAGES
/usr/share/locale/sr@latin/LC_MESSAGES/deadbeef.mo
/usr/share/locale/sv
/usr/share/locale/sv/LC_MESSAGES
/usr/share/locale/sv/LC_MESSAGES/deadbeef.mo
/usr/share/locale/te
/usr/share/locale/te/LC_MESSAGES
/usr/share/locale/te/LC_MESSAGES/deadbeef.mo
/usr/share/locale/tr
/usr/share/locale/tr/LC_MESSAGES
/usr/share/locale/tr/LC_MESSAGES/deadbeef.mo
/usr/share/locale/ug
/usr/share/locale/ug/LC_MESSAGES
/usr/share/locale/ug/LC_MESSAGES/deadbeef.mo
/usr/share/locale/uk
/usr/share/locale/uk/LC_MESSAGES
/usr/share/locale/uk/LC_MESSAGES/deadbeef.mo
/usr/share/locale/vi
/usr/share/locale/vi/LC_MESSAGES
/usr/share/locale/vi/LC_MESSAGES/deadbeef.mo
/usr/share/locale/zh_CN
/usr/share/locale/zh_CN/LC_MESSAGES
/usr/share/locale/zh_CN/LC_MESSAGES/deadbeef.mo
/usr/share/locale/zh_TW
/usr/share/locale/zh_TW/LC_MESSAGES
/usr/share/locale/zh_TW/LC_MESSAGES/deadbeef.mo
/usr/share/menu
/usr/share/menu/deadbeef

**Comment by DreaminginCodeZH** [comment]
Then it is a packaging issue - You need to get the header file for compilation, ideally by installing a package that ships it.

I checked the PPA repository for you, and found that you can install `deadbeef-plugins-dev` from the same repo to get these header files.

**Comment by amartin1911** [comment]
Thanks a lot! After installing `deadbeef-plugins-dev` I can compile mmkeys without issues.
