### ISSUE TITLE
Not Working on Gnome 3.26

### ISSUE THREAD

**Issue by jadenPete** [DreaminginCodeZH/deadbeef-gnome-mmkeys#6]
After upgrading to Gnome 3.26 on Arch Linux, I noticed that the plugin was not working. I launched `dbus-monitor --session` to see what was getting called, and found that `path=/org/gnome/Shell; interface=org.gnome.Shell; member=AcceleratorActivated` showed whenever I pressed a multimedia key.

uint32 173 is for pause
uint32 174 is for next
uint32 174 is for previous

Not sure what stop is, my laptop has no stop key.

**Comment by DreaminginCodeZH** [comment]
Please check if it's fixed now - I'm running GNOME 3.24 but tried a reasonable fix from googling "GNOME 3.26 media keys".

**Comment by jadenPete** [comment]
Works perfectly, thank you!
