### ISSUE TITLE
Cinnamon support

### ISSUE THREAD

**Issue by C0rn3j** [DreaminginCodeZH/deadbeef-gnome-mmkeys#9]
I've tried this plugin on Arch Linux with
cinnamon 4.0.8-1
deadbeef 0.7.2-4

and it doesn't seem to work. The mpris2-plugin does however

https://github.com/Serranya/deadbeef-mpris2-plugin

**Comment by C0rn3j** [comment]
>Did it work on Cinnamoon before? (I supposed so)

Didn't try until now.

> And can you find any log related?

I could find via QDbusViewer that Cinnamon seems to use the same dbus interface as gnome so it should work.

```
** (deadbeef:22690): WARNING **: 22:01:05.609: ddb_gnome_mmkeys, Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.MediaKeys was not provided by any .service files
```

![image](https://user-images.githubusercontent.com/1641362/50858599-209f3080-1391-11e9-8ff1-ca2f34e633c0.png)

**Comment by DreaminginCodeZH** [comment]
The message is about `org.gnome.SettingsDaemon` (note no `.MediaKeys`) not found as a service. I was expecting the code to fallback to the old bus name when the new one isn't found (NULL is returned as per https://developer.gnome.org/gio/stable/GDBusProxy.html#g-dbus-proxy-new-sync ), but it seems that this didn't happen (perhaps non-null is returned even if there is no such bus name in system).

Can you add some logging to confirm that `g_dbus_proxy_new_sync` returned a non-null value for the non-existent bus `org.gnome.SettingsDaemon.MediaKeys`? If so, is `dbus_error` null or non-null in this case?
And what if you swap the order of the two calls with different bus names (with and without `.MediaKeys`)?

I tried to find how other people are doing this compatibility check, however most changed I found (e.g. Totem, Rythmbox) was simply replacing the bus name, which makes them also not backwards/cinnamoon compatible.

**Comment by C0rn3j** [comment]
If I understand correctly, the first `g_dbus_proxy_new_sync` executes correctlyish on first try without error.
dbus_error seems to be NULL

```
          g_warning("dbus: custom error: %s\n", plugin.proxy);

** (deadbeef:12035): WARNING **: 01:52:02.142: dbus: custom error:  \xce\u001e\xealU
```

> And what if you swap the order of the two calls with different bus names (with and without .MediaKeys)?

Then mediakeys work!

Take my statements with a grain of salt as I'm a noob, so I might be deducting things wrong.

**Comment by DreaminginCodeZH** [comment]
That is weird - I was expecting `g_dbus_proxy_new_sync` to fail because according to your screenshot there is no service named `org.gnome.SettingsDaemon.MediaKeys`. Despite mentioning returning `NULL` upon error, GLib manual didn't mention what happens if a serivce doesn't exist when you create the proxy. And there just isn't too much documentation about it - maybe we need to dig into source about its behavior. I'm no GLib expert either :/

**Comment by DreaminginCodeZH** [comment]
After some more searching I believe `g_dbus_proxy_get_name_owner` shoukd do the trick. Will fix this soon.

**Comment by DreaminginCodeZH** [comment]
@C0rn3j Can you try the master branch? I suppose 392f442 should have fixed this.

**Comment by C0rn3j** [comment]
Looks like it did, thanks!
